In [1]:
import pandas as pd
import selenium

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

In [2]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
url = "https://www.fundamentus.com.br/resultado.php"

driver.get(url)

In [3]:
local_tabela = "/html/body/div[1]/div[2]/table"
elemento = driver.find_element("xpath", local_tabela)
tabela_html = elemento.get_attribute("outerHTML")

dataf = pd.read_html(str(tabela_html), thousands = ".", decimal = ",")[0]
dataf

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CFLU4,1000.00,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"8,88%","10,72%",1.10,"17,68%","32,15%",0.0,6.035100e+07,0.06,"8,14%"
1,CSTB3,150.00,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
2,CLAN3,0.00,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","-1,05%",0.0,1.012240e+09,0.00,"-63,96%"
3,PMET3,0.00,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","4,10%",0.0,-2.908630e+08,0.00,"37,74%"
4,CSTB4,147.69,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,PRBC4,14.54,502.29,40.26,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","8,02%",0.0,1.176410e+09,0.00,"-6,01%"
982,UBBR4,7.49,610.27,1.99,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
983,UBBR11,14.75,1201.81,3.91,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
984,UBBR3,18.00,1466.61,4.77,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
985,SQIA3,26.93,2700.43,3.70,3.607,"0,21%",1.476,26.62,42.55,-3.66,...,16.24,"8,48%","0,45%",1.44,"4,04%","0,14%",25845200.0,6.397490e+08,0.67,"46,25%"

In [4]:
dataf = dataf.set_index("Papel")
dataf = dataf[["Cotação", "EV/EBIT", "ROIC", "Liq.2meses"]]
dataf

        Cotação  EV/EBIT    ROIC  Liq.2meses
Papel
CFLU4   1000.00     0.00  17,68%         0.0
CSTB3    150.00     0.00  22,40%         0.0
CLAN3      0.00     0.00   0,00%         0.0
PMET3      0.00     0.00   0,00%         0.0
CSTB4    147.69     0.00  22,40%         0.0
...         ...      ...     ...         ...
PRBC4     14.54     0.00   0,00%         0.0
UBBR4      7.49     0.00   0,00%         0.0
UBBR11    14.75     0.00   0,00%         0.0
UBBR3     18.00     0.00   0,00%         0.0
SQIA3     26.93    46.34   4,04%  25845200.0

[986 rows x 4 columns]

In [5]:
dataf.info()

dataf["ROIC"] = dataf["ROIC"].str.replace("%", "")
dataf["ROIC"] = dataf["ROIC"].str.replace(".", "")
dataf["ROIC"] = dataf["ROIC"].str.replace(",", ".")
dataf["ROIC"] = dataf["ROIC"].astype(float)
display(dataf)

<class 'pandas.core.frame.DataFrame'>
Index: 986 entries, CFLU4 to SQIA3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Cotação     986 non-null    float64
 1   EV/EBIT     986 non-null    float64
 2   ROIC        986 non-null    object
 3   Liq.2meses  986 non-null    float64
dtypes: float64(3), object(1)
memory usage: 38.5+ KB

C:\Users\enzoc\AppData\Local\Temp\ipykernel_13824\3104574301.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  dataf["ROIC"] = dataf["ROIC"].str.replace(".", "")

        Cotação  EV/EBIT   ROIC  Liq.2meses
Papel
CFLU4   1000.00     0.00  17.68         0.0
CSTB3    150.00     0.00  22.40         0.0
CLAN3      0.00     0.00   0.00         0.0
PMET3      0.00     0.00   0.00         0.0
CSTB4    147.69     0.00  22.40         0.0
...         ...      ...    ...         ...
PRBC4     14.54     0.00   0.00         0.0
UBBR4      7.49     0.00   0.00         0.0
UBBR11    14.75     0.00   0.00         0.0
UBBR3     18.00     0.00   0.00         0.0
SQIA3     26.93    46.34   4.04  25845200.0

[986 rows x 4 columns]

In [6]:
dataf = dataf[dataf["Liq.2meses"] > 1000000]
dataf = dataf[dataf["EV/EBIT"] > 0]
dataf = dataf[dataf["ROIC"] > 0 ]

In [7]:
dataf["ranking_ev_ebit"] = dataf["EV/EBIT"].rank(ascending= True)
dataf["ranking_roic"] = dataf["ROIC"].rank(ascending= False)
dataf["ranking_total"] = dataf["ranking_ev_ebit"] + dataf["ranking_roic"]

dataf = dataf.sort_values("ranking_total").rank(ascending= True).astype(int)

dataf.head(10)

,Cotação,EV/EBIT,ROIC,Liq.2meses,ranking_ev_ebit,ranking_roic,ranking_total
Papel,,,,,,,
PSSA3,156,1,195,128,1,1,1
PETR4,165,4,186,194,4,9,2
PETR3,170,5,186,191,5,9,3
WIZC3,39,3,180,36,3,16,4
KEPL3,77,18,194,82,18,2,5
UNIP6,194,19,193,84,19,3,6
FESA4,183,10,182,65,10,14,7
CMIN3,18,16,185,97,16,11,8
VLID3,120,8,174,44,8,22,9
VALE3,191,9,171,195,9,25,10